language: python
python:
  - "3.6"
  - "3.7"
dist: bionic

before_install:
  - sudo apt-get update
  - sudo apt install -y libhunspell-dev hunspell-en-us

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run --source prosedecomposer setup.py test --verbose

after_success:
  - pip install coveralls
  - coveralls  # send coverage to coveralls.io

after_script:
  - coverage report                     # display coverage report on command line
  - pip install pycodestyle pyflakes
  - pyflakes . | tee >(wc -l)           # static analysis
  - pycodestyle --max-line-length=120 --statistics --count .  # static analysis